ALTER TYPE "BadgeCategory" ADD VALUE IF NOT EXISTS 'SOCIAL';
ALTER TYPE "BadgeCategory" ADD VALUE IF NOT EXISTS 'EVENT';

CREATE TYPE "BadgeKind" AS ENUM ('STANDARD', 'MILESTONE', 'EVENT', 'EXCLUSIVE');

ALTER TYPE "BadgeConditionKind" ADD VALUE IF NOT EXISTS 'LIBRARY_COUNT';
ALTER TYPE "BadgeConditionKind" ADD VALUE IF NOT EXISTS 'FAVORITES_COUNT';
ALTER TYPE "BadgeConditionKind" ADD VALUE IF NOT EXISTS 'PROFILE_COMPLETED';

ALTER TABLE "Badge" ADD COLUMN "kind" "BadgeKind" NOT NULL DEFAULT 'STANDARD';
